from Tkinter import *

class calcWindow:
	# def add(self, destination):

	def __init__(self, master):
		self.clearme = False
		window = Frame(master)		
		window.pack()
		self.r0c0 = Button(window, text = '+', command = lambda: self.add((0, 0))).grid(row = 0, column = 0)
		self.r0c1 = Button(window, text = '+', command = lambda: self.add((0, 1))).grid(row = 0, column = 1)
		self.r0c2 = Button(window, text = '+', command = lambda: self.add((0, 2))).grid(row = 0, column = 2)
		self.r0c3 = Button(window, text = '+', command = lambda: self.add((0, 3))).grid(row = 0, column = 3)
		self.r0c4 = Button(window, text = '+', command = lambda: self.add((0, 4))).grid(row = 0, column = 4)
		self.r0c5 = Button(window, text = '+', command = lambda: self.add((0, 5))).grid(row = 0, column = 5)
		self.r0c6 = Button(window, text = '+', command = lambda: self.add((0, 6))).grid(row = 0, column = 6)
		self.r0c7 = Button(window, text = '+', command = lambda: self.add((0, 7))).grid(row = 0, column = 7)
		self.r1c0 = Button(window, text = '+', command = lambda: self.add((1, 0))).grid(row = 1, column = 0)
		self.r1c1 = Button(window, text = '+', command = lambda: self.add((1, 1))).grid(row = 1, column = 1)
		self.r1c2 = Button(window, text = '+', command = lambda: self.add((1, 2))).grid(row = 1, column = 2)
		self.r1c3 = Button(window, text = '+', command = lambda: self.add((1, 3))).grid(row = 1, column = 3)
		self.r1c4 = Button(window, text = '+', command = lambda: self.add((1, 4))).grid(row = 1, column = 4)
		self.r1c5 = Button(window, text = '+', command = lambda: self.add((1, 5))).grid(row = 1, column = 5)
		self.r1c6 = Button(window, text = '+', command = lambda: self.add((1, 6))).grid(row = 1, column = 6)
		self.r1c7 = Button(window, text = '+', command = lambda: self.add((1, 7))).grid(row = 1, column = 7)
		self.r2c0 = Button(window, text = '+', command = lambda: self.add((2, 0))).grid(row = 2, column = 0)
		self.r2c1 = Button(window, text = '+', command = lambda: self.add((2, 1))).grid(row = 2, column = 1)
		self.r2c2 = Button(window, text = '+', command = lambda: self.add((2, 2))).grid(row = 2, column = 2)
		self.r2c3 = Button(window, text = '+', command = lambda: self.add((2, 3))).grid(row = 2, column = 3)
		self.r2c4 = Button(window, text = '+', command = lambda: self.add((2, 4))).grid(row = 2, column = 4)
		self.r2c5 = Button(window, text = '+', command = lambda: self.add((2, 5))).grid(row = 2, column = 5)
		self.r2c6 = Button(window, text = '+', command = lambda: self.add((2, 6))).grid(row = 2, column = 6)
		self.r2c7 = Button(window, text = '+', command = lambda: self.add((2, 7))).grid(row = 2, column = 7)
		self.r3c0 = Button(window, text = '+', command = lambda: self.add((3, 0))).grid(row = 3, column = 0)
		self.r3c1 = Button(window, text = '+', command = lambda: self.add((3, 1))).grid(row = 3, column = 1)
		self.r3c2 = Button(window, text = '+', command = lambda: self.add((3, 2))).grid(row = 3, column = 2)
		self.r3c3 = Button(window, text = '+', command = lambda: self.add((3, 3))).grid(row = 3, column = 3)
		self.r3c4 = Button(window, text = '+', command = lambda: self.add((3, 4))).grid(row = 3, column = 4)
		self.r3c5 = Button(window, text = '+', command = lambda: self.add((3, 5))).grid(row = 3, column = 5)
		self.r3c6 = Button(window, text = '+', command = lambda: self.add((3, 6))).grid(row = 3, column = 6)
		self.r3c7 = Button(window, text = '+', command = lambda: self.add((3, 7))).grid(row = 3, column = 7)
		self.r4c0 = Button(window, text = '+', command = lambda: self.add((4, 0))).grid(row = 4, column = 0)
		self.r4c1 = Button(window, text = '+', command = lambda: self.add((4, 1))).grid(row = 4, column = 1)
		self.r4c2 = Button(window, text = '+', command = lambda: self.add((4, 2))).grid(row = 4, column = 2)
		self.r4c3 = Button(window, text = '+', command = lambda: self.add((4, 3))).grid(row = 4, column = 3)
		self.r4c4 = Button(window, text = '+', command = lambda: self.add((4, 4))).grid(row = 4, column = 4)
		self.r4c5 = Button(window, text = '+', command = lambda: self.add((4, 5))).grid(row = 4, column = 5)
		self.r4c6 = Button(window, text = '+', command = lambda: self.add((4, 6))).grid(row = 4, column = 6)
		self.r4c7 = Button(window, text = '+', command = lambda: self.add((4, 7))).grid(row = 4, column = 7)
		self.r5c0 = Button(window, text = '+', command = lambda: self.add((5, 0))).grid(row = 5, column = 0)
		self.r5c1 = Button(window, text = '+', command = lambda: self.add((5, 1))).grid(row = 5, column = 1)
		self.r5c2 = Button(window, text = '+', command = lambda: self.add((5, 2))).grid(row = 5, column = 2)
		self.r5c3 = Button(window, text = '+', command = lambda: self.add((5, 3))).grid(row = 5, column = 3)
		self.r5c4 = Button(window, text = '+', command = lambda: self.add((5, 4))).grid(row = 5, column = 4)
		self.r5c5 = Button(window, text = '+', command = lambda: self.add((5, 5))).grid(row = 5, column = 5)
		self.r5c6 = Button(window, text = '+', command = lambda: self.add((5, 6))).grid(row = 5, column = 6)
		self.r5c7 = Button(window, text = '+', command = lambda: self.add((5, 7))).grid(row = 5, column = 7)
		self.r6c0 = Button(window, text = '+', command = lambda: self.add((6, 0))).grid(row = 6, column = 0)
		self.r6c1 = Button(window, text = '+', command = lambda: self.add((6, 1))).grid(row = 6, column = 1)
		self.r6c2 = Button(window, text = '+', command = lambda: self.add((6, 2))).grid(row = 6, column = 2)
		self.r6c3 = Button(window, text = '+', command = lambda: self.add((6, 3))).grid(row = 6, column = 3)
		self.r6c4 = Button(window, text = '+', command = lambda: self.add((6, 4))).grid(row = 6, column = 4)
		self.r6c5 = Button(window, text = '+', command = lambda: self.add((6, 5))).grid(row = 6, column = 5)
		self.r6c6 = Button(window, text = '+', command = lambda: self.add((6, 6))).grid(row = 6, column = 6)
		self.r6c7 = Button(window, text = '+', command = lambda: self.add((6, 7))).grid(row = 6, column = 7)
		self.r7c0 = Button(window, text = '+', command = lambda: self.add((7, 0))).grid(row = 7, column = 0)
		self.r7c1 = Button(window, text = '+', command = lambda: self.add((7, 1))).grid(row = 7, column = 1)
		self.r7c2 = Button(window, text = '+', command = lambda: self.add((7, 2))).grid(row = 7, column = 2)
		self.r7c3 = Button(window, text = '+', command = lambda: self.add((7, 3))).grid(row = 7, column = 3)
		self.r7c4 = Button(window, text = '+', command = lambda: self.add((7, 4))).grid(row = 7, column = 4)
		self.r7c5 = Button(window, text = '+', command = lambda: self.add((7, 5))).grid(row = 7, column = 5)
		self.r7c6 = Button(window, text = '+', command = lambda: self.add((7, 6))).grid(row = 7, column = 6)
		self.r7c7 = Button(window, text = '+', command = lambda: self.add((7, 7))).grid(row = 7, column = 7)


root = Tk()

# root.minsize(width = 200, height = 150)
# root.maxsize(width = 200, height = 150)
root.wm_title(u"\u265E" + " knightbot")

Nhat = calcWindow(root)
root.mainloop()